### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by mada41** [VideoSpike/nativescript-web-image-cache#1]
hi @bathejasumeet , great plugin 👍 
btw any plan for merge to https://github.com/triniwiz/nativescript-image-cache-it ?

**Comment by bathejasumeet** [comment]
Hello @mada41 ..thinking of integrating facebook fresco for android with this one, markups are way off with the plugin you mentioned

**Comment by mada41** [comment]
ok i see

**Comment by bathejasumeet** [comment]
Hello @mada41, @manijak  have added support for android in version 2.0 of the plugin. It works on NS 2.0, however, this is a breaking change, markups have been changed considerably to make sense on android, so you might have to change the code a little bit to make it work, please refer readme :)
