### ISSUE TITLE
Typescript/Angular2

### ISSUE THREAD

**Issue by ahalls** [VideoSpike/nativescript-web-image-cache#11]
Would like to see how to use the plugin with Typescript/Angular2

**Comment by kerbooo** [comment]
Yes I have same problem? How can we implement this plugin with TypeScript/Angular 2?

**Comment by zoeitsolutions** [comment]
+1

**Comment by ahalls** [comment]
This is what I did

Added the following lines to the`main.ts` file.
```
var imageCache = require("nativescript-web-image-cache");
registerElement("WebImage", () => imageCache.WebImage);
```

Then add this line into the html file where the image is to appear
```
      <WebImage  [src]='imageURL' class='page-image' stretch="aspectFill" > </WebImage>
 ```

**Comment by bathejasumeet** [comment]
I'll look into it

**Comment by timricker** [comment]
@ahalls, I'm getting the following when following your implementation:

 image.ios.sd_setImageWithURLCompleted is not a function. 

```
(In 'image.ios.sd_setImageWithURLCompleted(value, function () {
	                image.isLoading = false;
	            })', 'image.ios.sd_setImageWithURLCompleted' is undefined)
```

Any ideas?

@basumeet, I'm interested to know how you go looking into it.

This looks like a great plugin if it can be made Angular 2 + Typescript friendly.

**Comment by bathejasumeet** [comment]
Updated to v3.0
Added angular support
