### ISSUE TITLE
Fail to build app with the plugin

### ISSUE THREAD

**Issue by ADjenkov** [VideoSpike/nativescript-web-image-cache#15]
Trying to build {N} + Angular 2 (tns --version = 2.4.2) Android app with the plugin:

`node_modules/nativescript-web-image-cache/WebImageCache.d.ts(1,1): error TS2654:
 Exported external package typings file cannot contain tripleslash references. P
lease contact the package author to update the package definition.`

**Comment by bathejasumeet** [comment]
I'll look into it

**Comment by bathejasumeet** [comment]
I'll look into it

**Comment by bathejasumeet** [comment]
Resolved in 3.2
