### ISSUE TITLE
Element for WebImage already registered 

### ISSUE THREAD

**Issue by ADjenkov** [VideoSpike/nativescript-web-image-cache#16]
If I do this in main.ts:

`application.on(application.launchEvent, function (args: application.ApplicationEventData) {
    initializeOnAngular();
});`

Every time the application is resumed from previous BACK button 'exit' -  the app will crash with "Element for WebImage already registered " message. I think you should check if the element is already registered.

**Comment by bathejasumeet** [comment]
resolved in v3.4
