### ISSUE TITLE
Question regarding clearing caches

### ISSUE THREAD

**Issue by ntucakovic** [VideoSpike/nativescript-web-image-cache#17]
Hello,

First of all, it was a breeze setting up this plugin. Seems to work right away, {N} + ng2.

I just have an issue regarding default cached image lifetime. Says 30 days on Android and 7 on iOS. Does that mean that I don't have to use `clearCache()` method or?

Anyway, I'm trying to set it to 7 days on both systems. Care to point me in the right direction?

Thank you very much 👍

**Comment by bathejasumeet** [comment]
you don't have to `clearCache()` after lifetime, it automatically clears it, those are default timelines provided by respective native cache libs. 
I'll try exposing the lifetime API in the upcoming release.

**Comment by ntucakovic** [comment]
That's great. Thank you.

Just realized another feature that would be great.

Since WebImage is probably a wrapper around Image element, we could extend it to accept placeholderImage parameter, which is resolved to a local app image, which is shown while original image isLoading. Overkill or useful feature? Either way, it would be optional whether people will use it. What do you think?

I'll do a component around WebImage for that feature in meantime.

**Comment by bathejasumeet** [comment]
You can do that right now as well, not with the image cache api though.

Overlay image over one another, at the same position. Till the web image loads, the image underneath it is displayed, which acts as a placeholder.

Nonetheless, I'll look into it as well.

Thanks

**Comment by joeizy** [comment]
Placeholder would be awesome!

**Comment by bathejasumeet** [comment]
Added placeholder and lifetime specification support in v4.0
