### ISSUE TITLE
Rounded corners not possible

### ISSUE THREAD

**Issue by manijak** [VideoSpike/nativescript-web-image-cache#18]
Setting border-radius via CSS does not apply here, like it does on the stock Image module (in order to create a rounded-image).

**Comment by bathejasumeet** [comment]
will look into it

**Comment by manijak** [comment]
No need, created a PR https://github.com/VideoSpike/nativescript-web-image-cache/pull/19

**Comment by bathejasumeet** [comment]
@manijak 
Thanks a ton! :)

I'll test it and merge it by this weekend, I hope that is okay :)

**Comment by bathejasumeet** [comment]
I'll also try to see if equivalent is possible in SDWebImageCache (the ios equivalent)

**Comment by bathejasumeet** [comment]
Merged, let this issue be open for now, I'll see if equivalent is possible for iOS

**Comment by manijak** [comment]
Ok, for iOS it works by using a css class and setting border-radius half the size of the image. Not sure if SDWebImage has a similar property like Fresco.

**Comment by bathejasumeet** [comment]
I don't think it will have a similar prop. SDWebImage is extension on normal UIImage, Objective C category to be specific.  If css class works for native UIImage, it should work for SDWebImage. closing this.
