### ISSUE TITLE
WebPack Build not showing Images

### ISSUE THREAD

**Issue by pluservice** [VideoSpike/nativescript-web-image-cache#20]
On Android  normal build is OK while webPack bundle build does not show Images

  "dependencies": {
    "@angular/common": "2.4.3",
    "@angular/compiler": "2.4.3",
    "@angular/core": "2.4.3",
    "@angular/forms": "2.4.3",
    "@angular/http": "2.4.3",
    "@angular/platform-browser": "2.4.3",
    "@angular/platform-browser-dynamic": "2.4.3",
    "@angular/router": "3.4.3",
    "@ngrx/core": "^1.2.0",
    "@ngrx/effects": "^2.0.0",
    "@ngrx/router-store": "^1.2.5",
    "@ngrx/store": "^2.2.1",
    "angular2-moment": "^1.2.0",
    "nativescript-angular": "1.4.0",
    "nativescript-theme-core": "^1.0.2",
    "nativescript-web-image-cache": "^3.4.0",
    "reflect-metadata": "~0.1.8",
    "reselect": "^2.5.4",
    "rxjs": "~5.0.1",
    "tns-core-modules": "2.5.0"
  },

**Comment by bathejasumeet** [comment]
I just resolved this in #12 , strange, can provide the sample app that fails?

Thanks

**Comment by williamltb** [comment]
If you use uglifyjs to further reduce the size of bundle in webpack, you must excludes WebImage from mangle. 

See the following:

`
var excludesMangle = nsWebpack.uglifyMangleExcludes;
excludesMangle.push('DropDown', 'WebImage');
`
...

`

        var compress = platform !== "android";
        plugins.push(new webpack.optimize.UglifyJsPlugin({
            mangle: {
                except: excludesMangle,
            },
            compress: compress,
            comments: false
        }));`

**Comment by pluservice** [comment]
Here it is the app:
https://we.tl/gGZpmPiRjs

"tns run android " is ok

"npm run start-android-bundle" images are missing

**Comment by williamltb** [comment]
During Webpack, the compilation will start from main.aot.ts instead of main.ts. My recommendation is to move the (initializationOnAngular) in the app.module.ts

**Comment by bathejasumeet** [comment]
@pluservice 

Updated docs to intialize in the bootstrapped Component class constructor.
Nothing else seemed to work. This has to do with the dependency graph that webpack generates.
Thanks for the info. Seems to work after initialization in the bootstrapped component.

**Comment by iguissouma** [comment]
Hello,
I have same problem Image not shown when building with webpack.
Initializing on bootstrap component don't help, I got the below error:
<img width="260" alt="2017-06-22_17h47_17" src="https://user-images.githubusercontent.com/9085108/27443310-f0b4002a-5772-11e7-9620-f2da082e75b4.png">

NativeScript 3.0.1
Angular 4

Any idea How to fix this issue?

**Comment by bathejasumeet** [comment]
@iguissouma -- works, just tested on my local dev with NS 3.0.3 , can you provide the repo git if it is not a private repo ?

**Comment by iguissouma** [comment]
@bathejasumeet I updated NS from 3.0.1 to 3.0.3, removed the android platform and added again.
I initialize plugin on AppComponent.
It works now.

thanks, keep up the great work.
