### ISSUE TITLE
Android local images not shown 

### ISSUE THREAD

**Issue by nicHoch** [VideoSpike/nativescript-web-image-cache#35]
Hi 
if I set the `WebImage.src` attribute to a local image on Android it is not shown.
Is working on iOS as expected.

**Comment by chauch-a** [comment]
Same for me when having a local url like '/data/user/0/packageName/files/dir/image.jpeg'. Setting it for src or placeholder just shows nothing and no error is thrown

**Comment by shabib3** [comment]
@bathejasumeet 
Same here...
Any update about it?

**Comment by OPADA-Eng** [comment]
any fix for this ?

**Comment by bathejasumeet** [comment]
Just verified, it works for '~/..' and 'res://' paths as specified at https://docs.nativescript.org/ui/images . Also, while using 'res://'  the extension  eg. '.png' should not be specified.
Can you please explain the problem in detail?

Regards,
Sumeet

**Comment by bathejasumeet** [comment]
I assume this works, please elaborate and reopen the issue if it does not.
Regards,
Sumeet
