### ISSUE TITLE
iOS images not shown

### ISSUE THREAD

**Issue by alexandruantonica** [VideoSpike/nativescript-web-image-cache#38]
Hi,

The plugin works on Android (device/emulator) but it doesn't show the image from `src` on iOS. 

`nativescript` : `3.1.3`
`tns-core-modules` : `3.1.1` 
`tns-ios` : `3.2.0` (the same for android)
`angular...` : `4.1.3`
`nativescript-web-image-cache` : `^4.2.2`
If you need more information about the project, let me know. 

I use the markup like that : 
`<WebImage stretch="aspectFit" src="{{ data.imageUri }}" placeholder="res://local_image" width="120" height="120" [rounded]="true"></WebImage>` 
The app shows me the `placeholder` image but not the `src` image. 
What should I do ? 

Thanks.

**Comment by alexandruantonica** [comment]
@bathejasumeet can you help with this bug, please ?

**Comment by bathejasumeet** [comment]
@alexandruantonica 

what is data.imageUri ? is it a resource from the web ? can I please get the sample link to simulate on my end ?

Thanks

**Comment by alexandruantonica** [comment]
Hi @bathejasumeet 
The `data.imageUri` is a string with a URL like this `http://via.placeholder.com/1200x800`. 
I tried with my dynamic generated URL but I also tried with the example above.

Thanks.

**Comment by bathejasumeet** [comment]
Hi @alexandruantonica 
can I get your package.json to check the versions?
I am getting incompatibility errors (typescript compilation and iOS internal undefined errors) while   trying to start up the app for the config you specified.

Thanks

**Comment by alexandruantonica** [comment]
Hi @bathejasumeet 

This is my package.json
```
{
  "nativescript": {
    "tns-android": {
      "version": "3.2.0"
    },
    "tns-ios": {
      "version": "3.2.0"
    }
  },
  "dependencies": {
    "@angular/animations": "4.1.3",
    "@angular/common": "4.1.3",
    "@angular/compiler": "4.1.3",
    "@angular/core": "4.1.3",
    "@angular/forms": "4.1.3",
    "@angular/http": "4.1.3",
    "@angular/platform-browser": "4.1.3",
    "@angular/router": "4.1.3",
    "core-js": "2.5.0",
    "nativescript-accelerometer": "2.0.1",
    "nativescript-angular": "3.1.3",
    "nativescript-appversion": "1.4.1",
    "nativescript-bottombar": "3.0.5",
    "nativescript-camera": "3.0.2",
    "nativescript-cardview": "2.0.2",
    "nativescript-contacts-lite": "0.2.3",
    "nativescript-email": "1.5.1",
    "nativescript-imagepicker": "3.0.6",
    "nativescript-iqkeyboardmanager": "1.1.0",
    "nativescript-loading-indicator": "2.3.2",
    "nativescript-localstorage": "1.1.5",
    "nativescript-mixpanel": "1.0.8",
    "nativescript-ngx-fonticon": "2.2.3",
    "nativescript-pager": "5.0.5",
    "nativescript-permissions": "1.2.3",
    "nativescript-phone": "1.3.1",
    "nativescript-status-bar": "1.1.1",
    "nativescript-telerik-ui": "3.0.4",
    "nativescript-theme-core": "1.0.4",
    "nativescript-timedatepicker": "1.2.0",
    "nativescript-toast": "1.4.6",
    "nativescript-trace-raven": "1.0.0",
    "nativescript-web-image-cache": "^4.2.2",
    "nativescript-webworkers": "^1.0.4",
    "reflect-metadata": "0.1.8",
    "rxjs": "5.4.3",
    "tns-core-modules": "3.1.1",
    "tns-core-modules-widgets": "3.1.1",
    "zone.js": "0.8.17"
  },
  "devDependencies": {
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "lazy": "1.0.11",
    "nativescript-dev-android-snapshot": "^0.*.*",
    "nativescript-dev-typescript": "0.5.0",
    "tns-platform-declarations": "3.1.1",
    "typescript": "2.4.2"
  }
}
```

**Comment by bathejasumeet** [comment]
Sorry for the late reply, busy week.

try https links, this one works -- it's from the same website https://via.placeholder.com/1200x800. This has to do with iOS guidelines. You can disable this in info.plist.

Let me know if it works.

Thanks,
Sumeet

**Comment by hettiger** [comment]
This is probably related with #39

**Comment by bathejasumeet** [comment]
This seems to be an issue with ssl, apple does not inherently allow http resources, need to enable them in info.plist. If the issue still persists, let me know. Works on 4.2.4
