### ISSUE TITLE
Can't build project that incudes 4.2.5

### ISSUE THREAD

**Issue by Burgov** [VideoSpike/nativescript-web-image-cache#45]
Since today, I'm getting the following error when running with --bundle:

```
Module not found: Error: Can't resolve 'nativescript-web-image-cache' in '/Users/build/myagent/_work/1/s/app'
```

Switching back to 4.2.4 fixes the issue.

**Comment by bathejasumeet** [comment]
Will fix this tonight

**Comment by davecoffin** [comment]
Getting the same thing.

**Comment by davecoffin** [comment]
This looks like the only change that could be meaningful wrt this issue:
https://github.com/VideoSpike/nativescript-web-image-cache/commit/23a92546ad6f6a1887e75503bf53092d7cd1fef4

**Comment by bathejasumeet** [comment]
updated, please verify
