### ISSUE TITLE
Where are the TypeScript sources?

### ISSUE THREAD

**Issue by EddyVerbruggen** [VideoSpike/nativescript-web-image-cache#46]
Hi!

I love this plugin and use it in several apps, and would like to contribute. However, I don't see the typeScript source files, only the transpile JS files with [sourcemaps](https://github.com/VideoSpike/nativescript-web-image-cache/blob/28606c7d69f917c6d05830c17004b4d093517e70/web-image-cache.common.js#L21).

Can you please publish the TS files to GitHub?

Thanks!
Eddy

**Comment by bathejasumeet** [comment]
Hi, I will upload them over this weekend. I hope that is okay.

,
Sumeet

**Comment by EddyVerbruggen** [comment]
Of course, that would be great!

**Comment by bathejasumeet** [comment]
added
