### ISSUE TITLE
Cant bundle app Nativescript 4.1.1 nativescript-web-image-cache 4.2.6

### ISSUE THREAD

**Issue by Dinushasilva** [VideoSpike/nativescript-web-image-cache#53]
When i try to bundle and uglify the app it says **Module not found: Error: Can't resolve 'nativescript-angular/element-registry'**

I 'm using typescript not angularjs.

```
ERROR in ../node_modules/nativescript-web-image-cache/web-image-cache.js
Module not found: Error: Can't resolve 'nativescript-angular/element-registry' in  @ ../node_modules/nativescript-web-image-cache/web-image-cache.js 148:31-79
 @ ./app.ts
```

**Comment by cryptonator000** [comment]
same issue here

**Comment by Dinushasilva** [comment]
@cryptonator000 nop :(

**Comment by cryptonator000** [comment]
It seems that the plugin still works.
It is not a breaking error

**Comment by Dinushasilva** [comment]
@cryptonator000 plugin is working, the only problem is when you bundle it for production it's not working.

**Comment by asqwrd** [comment]
this issue exist still using nativescript-vue.  Commenting out the code for initializeOnAngular fixes it which means this is trying to load angular even tho angular does not exist.

**Comment by EddyVerbruggen** [comment]
Ran into this issue today as well, opened PR #64.
