### ISSUE TITLE
Compatible with Angular 2?

### ISSUE THREAD

**Issue by shanermr** [VideoSpike/nativescript-web-image-cache#6]
Does this plugin work with Angular2? 
Image never loads. Am I doing something wrong?

main.ts
`if (application.android) {`
    `application.onLaunch = function (intent) {`
        `console.log('in  launch');`
        `imageCache.initialize();`
    `};`
`}
`

Component: 
`import {registerElement} from "nativescript-angular/element-registry";`
 `registerElement("WebImage", () => require("nativescript-web-image-cache").WebImage);`

` <WebImage stretch="fill" 
             src="http://nprock.rmrdevelopment.com/content/testmessage.jpg">
             </WebImage>  `

**Comment by leocaseiro** [comment]
Hi @shanermr, I believe you are trying on Android as you don't need to start on iOS.

fresco needs to be started before your bootstrap. so add before that, like so:

```javascript
if (application.android) {
    application.onLaunch = function (intent) {
        imageCache.initialize();
    };
}

nativeScriptBootstrap(yourApp,[]);
```

**Comment by blaur** [comment]
He already copied in that he initializes in mail.ts?

I am experiencing the same problem.

**Comment by shanermr** [comment]
@leocaseiro life saver! I had it below my nativeScriptBootstrap line. Moved it directly below my import lines and working as expected.

**Comment by blaur** [comment]
@shanermr  Do you just require the application module in the following way:

var applicationModule = require("application");

**Comment by shanermr** [comment]
Yep

`var application = require("application");`
`var imageCache = require("nativescript-web-image-cache");`

`if (application.android) {
    application.onLaunch = function (intent) {
        console.log('in  launch');
        imageCache.initialize();
    };
}`

`nativeScriptBootstrap(AppComponent,`

**Comment by blaur** [comment]
Thanks a lot to both of you!

It works like a charm! ;)
