### ISSUE TITLE
Fallback to Image instead of WebImage in case the value is a local image?

### ISSUE THREAD

**Issue by NordlingArt** [VideoSpike/nativescript-web-image-cache#8]
I feel like this is necessary because not always are images a URL. Else I need to create two elements,  as in one being a WebImage and another an Image depending on a specific condition:

```xml
<IC:WebImage src="{{ image }}" visibility="{{ isURL ? 'visible' : 'collapsed' }}" />
<Image src="{{ image }}" visibility="{{ isURL ? 'collapsed' : 'visible' }}" />
```

**Comment by bathejasumeet** [comment]
Hi, I see where you are coming from, okay.. Give me a week, I'll integrate it, thanks for feedback

**Comment by bathejasumeet** [comment]
The reason I am asking for a week is because I have a couple of other things in mind that I want to add to it

**Comment by NordlingArt** [comment]
@bathejasummet - Hi, thanks! Sounds good, no rush :)

**Comment by bathejasumeet** [comment]
@NordlingArt Done, upgraded, handles local images

**Comment by NordlingArt** [comment]
@bathejasumeet - Nice, thanks!
